# Generated by Django 4.2.30 on 2026-08-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(max_length=50)),
                ('combustivel', models.CharField(max_length=30)),
                ('cambio', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('vendido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='veiculos.marca')),
            ],
        ),
    ]
