# Generated by Django 4.2.30 on 2026-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_fotoveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='slug',
            field=models.SlugField(default='veiculo', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
