# Generated by Django 4.2.30 on 2026-08-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0003_veiculo_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fotoveiculo",
            options={"ordering": ("ordem", "id")},
        ),
    ]
