# Generated by Django 4.2.30 on 2026-08-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_fotoveiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
